FORMAT: 1A
HOST: http://sandbox.cherehapa.ru/v2/

#API проекта "Черехапа Страхование" v2.0 - Общая схема работы с API v2.0

## Схема работы с API v2.0
API v.2 строится на базе RESTful схемы, т.е., в целом обращение идет по одним и тем же адресам, а действие, выполняемое через API определяется указанным в запросе HTTP-методом.
Обозначения:
- [api_base] - базовый адрес конкретного API. Например: [HOST]
- [resource] - название ресурса (объекта), с которым ведется работа. Например: country или order
- [function] - идетификатор дополнительной функции действия над объектом
- [id] - уникальный код элемента в базе данных
- [] - необязательные параметры

## Перечень общих методов API


| Название метода    | Описание                                               | URL                        |HTTP-метод | Пример URL |                            
|--------------------|--------------------------------------------------------|----------------------------|-----------|------------|
| index              | Получение перечня объектов                             | api_base/resource      | GET       | http://api.staging.cherehapa.ru/v2/country |
| store              | Создание нового объекта                                | api_base/resource      | POST      | http://api.staging.cherehapa.ru/v2/country |
| show               | Получение подробных данных об объекте                  | api_base/resource/id | GET       | http://api.staging.cherehapa.ru/v2/country/1 |
| update             | Обновление свойств объекта                             | api_base/resource/id | PUT       | http://api.staging.cherehapa.ru/v2/country/1 |
| destroy            | Удаление объекта из базы или отмена действия объекта   | api_base/resource/id | DELETE    | http://api.staging.cherehapa.ru/v2/country/1 |